id = "warm-light"
name = "Warm Light"
version = "0.0.1"
schema_version = 1
authors = ["Yang Gang <yanggang.uefi@gmail.com>"]
description = "Warm Light theme for the Zed code editor."
repository = "https://github.com/YangGangUEFI/zed-theme-warm-light"
